defmodule AdventOfCode.Day08Test do
  use ExUnit.Case

  test "correctly finds and counts all anti-nodes without harmonics" do
    input = """
    ..........
    ..........
    ..........
    ....a.....
    ........a.
    .....a....
    ..........
    ..........
    ..........
    ..........
    """

    assert(AdventOfCode.Day08.antinodes_count_without_harmonics(input) == 4)

    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    assert(AdventOfCode.Day08.antinodes_count_without_harmonics(input) == 14)
  end

  test "correctly finds and counts all anti-nodes with harmonics" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    assert(AdventOfCode.Day08.antinodes_count_with_harmonics(input) == 34)
  end
end
