defmodule AdventOfCode.Day6Test do
  use ExUnit.Case

  test "correctly counts the number of distinctive guard patrol positions" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert(AdventOfCode.Day6.count_distinctive_guard_patrol_positions(input) == 41)
  end

  test "correctly counts the number of possible obstacle locations that cause a loop" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert(AdventOfCode.Day6.count_possible_object_locations_that_cause_a_loop(input) == 6)
  end
end
